std_msgs/Header header

float32 m_value             # [0, 65536]
float32 q_value             # [0, 65536]
float32 cda_value           # [0, 16]
float32 peak_of_gaussian    # [0, 65536]
float32 std_of_gaussian     # [0, 16]
float32 p_value             # [0, 4096]
float32 i_value             # [0, 4096]
float32 d_value             # [0, 4096]
float32 n_value             # [0, 1]
float32 pid_limit_value     # [0, 65536]
